apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-api
  namespace: service-requests-api
  labels:
    app: service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-api
  template:
    metadata:
      labels:
        app: service-api
    spec:
      imagePullSecrets:
        - name: ghcr-regcred
      containers:
        - name: main
          image: ghcr.io/uvarc/service-api:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: service-api-secrets
                  key: MONGO_HOST
            - name: MONGO_ROOT
              valueFrom:
                secretKeyRef:
                  name: service-api-secrets
                  key: MONGO_ROOT
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: service-api-secrets
                  key: MONGO_PASS
            - name: DEBUG_SVCREQ
              valueFrom:
                secretKeyRef:
                  name: service-api-secrets
                  key: DEBUG_SVCREQ
            - name: API_CLIENT_KEYS
              valueFrom:
                secretKeyRef:
                  name: service-api-secrets
                  key: API_CLIENT_KEYS
            - name: ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: service-api-secrets
                  key: ADMIN_KEY
